site_name: PyStatPower 帮助文档
site_url: https://pystatpower.github.io/PyStatPower-Docs
repo_url: https://github.com/PyStatPower/PyStatPower
repo_name: PyStatPower
edit_uri: https://github.com/PyStatPower/PyStatPower-Docs/blob/main/docs
site_description: PyStatPower 是一个用于统计领域功效分析的 Python 库。
site_author: PyStatPower
copyright: Copyright © 2024 PyStatPower
theme:
  name: material
  language: zh
  features:
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
  custom_dir: overrides

nav:
  - 主页: index.md
  - 安装: install.md
  - 使用: usage.md
  - API:
    - api/index.md
    - 核心模块:
      - api/interval.md
      - api/exception.md
    - 实用模块:
      - api/procedures/one_sample_proportion.md

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md

extra:
  social:
    - icon: simple/github
      link: https://github.com/PyStatPower/PyStatPower
      name: Github 仓库
    - icon: simple/gmail
      link: mailto:openpower2024@gmail.com
      name: 邮件联系
  version:
    provider: mike

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search:
      lang:
        - en
        - zh
      jieba_dict: dict.txt
  - tags:
      tags_file: tags.md
  - mike:
      # These fields are all optional; the defaults are as below...
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_datetime
      timezone: Asia/Shanghai
      locale: zh
      fallback_to_build_date: true
  - git-committers:
      repository: PyStatPower/PyStatPower-Docs
      branch: main
